command: "rpg"
地下城世界: "dungeon"

掉落材料: { 's_rpg:magic_stone_fragment': 1.0 }
等级原掉落材料倍率: 1.5
等级击杀经验倍率: 10.0

玩家升级经验倍率: 1.2
玩家升级经济倍率: 1.2
玩家升级需要经验: 1000
玩家升级需要经济: 10000.0

装备升级材料: { 's_rpg:magic_stone': 10 }
装备升级材料倍率: 1.2
装备升级经济倍率: 1.2
装备升级需要经济: 1000.0

剑每级提升攻击: 2.0
盔甲每级提升血量: 2.0

等级压制倍率: 0.2

玩家刷新最大范围: 500

怪物最低等级: 1
怪物最高等级: 50
怪物等级浮动: 5

刷怪检测范围: 48
刷怪检测数量: 15
刷怪检测间隔: 20
刷怪清理范围: 64
刷怪清理最大范围: 128
刷怪范围: 32
安全区域半径: 24
刷怪类型:
  - { 名称: 骷髅, 类型: Skeleton, 权重: 100 }
  - { 名称: 爬行者, 类型: Creeper, 权重: 40 }
  - { 名称: 僵尸, 类型: Zombie, 权重: 60 }
  - { 名称: 蜘蛛, 类型: Spider, 权重: 40 }
  - { 名称: 洞穴蜘蛛, 类型: CaveSpider, 权重: 40 }
  - { 名称: 末影人, 类型: Enderman, 权重: 40 }
  - { 名称: 女巫, 类型: Witch, 权重: 30 }
  - { 名称: 烈焰人, 类型: Blaze, 权重: 25 }
  - { 名称: 岩浆怪, 类型: MagmaCube, 权重: 20 }
  - { 名称: 恶魂, 类型: Ghast, 权重: 15 }
  - { 名称: 凋灵骷髅, 类型: WitherSkeleton, 权重: 40 }
  - { 名称: 僵尸猪人, 类型: ZombiePigman, 权重: 80 }
  - { 名称: 幻翼, 类型: Phantom, 权重: 15 }
  - { 名称: 掠夺者, 类型: Pillager, 权重: 55 }
  - { 名称: 卫道士, 类型: Vindicator, 权重: 40 }
  - { 名称: 唤魔者, 类型: Evoker, 权重: 15 }
  - { 名称: 劫掠兽, 类型: Ravager, 权重: 10 }
  - { 名称: 潜影贝, 类型: Shulker, 权重: 20 }
  - { 名称: 恼鬼, 类型: Vex, 权重: 15 }
  - { 名称: 流浪者, 类型: Stray, 权重: 35 }
  - { 名称: 尸壳, 类型: Husk, 权重: 40 }
  - { 名称: 溺尸, 类型: Drowned, 权重: 40 }
  - { 名称: 猪灵, 类型: Piglin, 权重: 50 }
  - { 名称: 猪灵蛮兵, 类型: PiglinBrute, 权重: 15 }
  - { 名称: 凋灵, 类型: Wither, 权重: 1 }
  - { 名称: 末影龙, 类型: EnderDragon, 权重: 1 }
  - { 名称: 蠹虫, 类型: Silverfish, 权重: 5 }

物品刷新概率: 0.5
容器物品:
  - { 物品: "s_rpg:magic_stone_fragment", 最小数量: 1,最大数量: 3,权重: 100 }
  - { 物品: "s_rpg:tp_magic_scroll", 最小数量: 1,最大数量: 1,权重: 10 }
  - { 物品: "minecraft:elytra", 最小数量: 1,最大数量: 1,权重: 1 }
  - { 物品: "minecraft:torch", 最小数量: 1,最大数量: 64,权重: 50 }
  - { 物品: "minecraft:totem_of_undying", 最小数量: 1,最大数量: 1,权重: 10 }
  - { 物品: "minecraft:experience_bottle", 最小数量: 1,最大数量: 16,权重: 30 }
  - { 物品: "minecraft:diamond", 最小数量: 1,最大数量: 5,权重: 20 }
  - { 物品: "minecraft:netherite_ingot", 最小数量: 1,最大数量: 1,权重: 8 }
  - { 物品: "minecraft:oak_planks", 最小数量: 1,最大数量: 64,权重: 120 }
  - { 物品: "minecraft:golden_carrot", 最小数量: 1,最大数量: 16,权重: 30 }